//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopRuou.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DatHang_ChiTiet
    {
        public int ID { get; set; }
        [Display(Name = "Mã đặt hàng")]
        [Required(ErrorMessage = "Mã đặt hàng không được bỏ trống!")]
        public Nullable<int> DatHang_ID { get; set; }
        [Display(Name = "Sản phẩm")]
        [Required(ErrorMessage = "Sản phẩm không được bỏ trống!")]
        public Nullable<int> SanPham_ID { get; set; }
        [Display(Name = "Số lượng")]
        [Required(ErrorMessage = "Số lượng không được bỏ trống!")]
        public Nullable<short> SoLuong { get; set; }
        [Display(Name = "Đơn giá")]
        [Required(ErrorMessage = "Đơn giá không được bỏ trống!")]
        public Nullable<int> DonGia { get; set; }
    
        public virtual DatHang DatHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
