//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopRuou.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatHang()
        {
            this.DatHang_ChiTiet = new HashSet<DatHang_ChiTiet>();
        }
    
        public int ID { get; set; }
        public Nullable<int> TaiKhoan_ID { get; set; }
        public Nullable<int> KhachHang_ID { get; set; }
        [Display(Name = "Điện thoại đặt hàng")]
        [DataType(DataType.PhoneNumber)]
        [Required(ErrorMessage = "Số điện thoại không được bỏ trống.")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Số điện thoại không đúng định dạng.")]
        public string DienThoaiGiaoHang { get; set; }
        [Display(Name = "Điạ chỉ giao hàng")]
        [Required(ErrorMessage = "Địa chỉ giao hàng không được bỏ trống!")]
        public string DiaChiGiaoHang { get; set; }
        [Display(Name = "Ngày nhập")]
        [Required(ErrorMessage = "Ngày nhập không được bỏ trống!")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NgayDatHang { get; set; }
        [Display(Name = "Tình trạng")]
        [Required(ErrorMessage = "Tình trạng không được bỏ trống!")]
        public Nullable<short> TinhTrang { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatHang_ChiTiet> DatHang_ChiTiet { get; set; }
    }
}
